<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.study.bookcafe.book.BorrowTest" tests="1" skipped="0" failures="1" errors="0" timestamp="2024-11-12T10:54:42" hostname="김도니" time="0.089">
  <properties/>
  <testcase name="도서가 현재 대출가능한 상태인지 확인한다. (도서의 현재 대출가능수량 확인" classname="com.study.bookcafe.book.BorrowTest" time="0.089">
    <failure message="org.opentest4j.AssertionFailedError: &#13;&#10;expected: false&#13;&#10; but was: true" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: 
expected: false
 but was: true
	at java.base@17.0.11/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base@17.0.11/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base@17.0.11/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base@17.0.11/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at app//com.study.bookcafe.book.BorrowTest.checkBookStatusForBorrow(BorrowTest.java:18)
	at java.base@17.0.11/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base@17.0.11/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@17.0.11/java.util.ArrayList.forEach(ArrayList.java:1511)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
